### ISSUE TITLE
Otp save Update Fail

### ISSUE THREAD

**Issue by shubhanshu-02** [SohamKukreti/getyoattendance#2]
Meme appeared for a moment and suddenly I got this error
![image](https://github.com/user-attachments/assets/b5688dac-78f2-48e0-a2fb-666c89c9fea0)

**Comment by roshankraveendrababu** [comment]
please i assign me this issue i will solve the error and make the code run efficiently

**Comment by SohamKukreti** [comment]
> please i assign me this issue i will solve the error and make the code run efficiently

Okay :+1:
