### ISSUE TITLE
Change in absent classes

### ISSUE THREAD

**Issue by shubhanshu-02** [SohamKukreti/getyoattendance#5]
Has there been a change in the absent classes fetched from the portal?

Earlier it showed absent classes of tutorial and lecture combined-
![WhatsApp Image 2024-10-10 at 03 12 40_41ba5f79](https://github.com/user-attachments/assets/9e594a19-afe9-4cce-8ea0-0552716bf3e3)
(4 absent classes here)

Now it shows this-
![image](https://github.com/user-attachments/assets/8b718e75-4379-4112-b6f5-7c29f09579f4)
(1 absent class here)

**Comment by SohamKukreti** [comment]
Fixed it by displaying absent classes for tutorial and lecture separately in latest commit
